// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Vcaloriestable: typeof import('./../components/organisms/VCaloriesTable/vcaloriestable.vue')['default']
    Vdialogremove: typeof import('./../components/organisms/VDialogRemove/vdialogremove.vue')['default']
    Vformnutrition: typeof import('./../components/organisms/VFormNutrition/vformnutrition.vue')['default']
    Vinput: typeof import('./../components/atoms/VInput/vinput.vue')['default']
    Vlayout: typeof import('./../components/templates/VLayout/vlayout.vue')['default']
    Vnavbar: typeof import('./../components/organisms/VNavbar/vnavbar.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
